<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-08T07:11:01 IST" name="Default suite" finished-at="2022-09-08T07:11:01 IST" duration-ms="43">
    <groups>
    </groups>
    <test started-at="2022-09-08T07:11:01 IST" name="Default test" finished-at="2022-09-08T07:11:01 IST" duration-ms="43">
      <class name="calculator_testcases.CalculatorTest">
        <test-method signature="throwingNegativeNumberErrors()[pri:0, instance:calculator_testcases.CalculatorTest@71b1176b]" started-at="2022-09-08T07:11:01 IST" name="throwingNegativeNumberErrors" description="Throws error if negative number exists in input string" finished-at="2022-09-08T07:11:01 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- throwingNegativeNumberErrors -->
      </class> <!-- calculator_testcases.CalculatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
